### ISSUE TITLE
While running redfishtool, i am getting No module named redfishtoollib but installed all necessary packages

### ISSUE THREAD

**Issue by Ganesan149** [DMTF/Redfishtool#101]
lab@lab-Precision-5510-lab3:~/ganesan/Redfish-Usecase-Checkers$ redfishtool
Traceback (most recent call last):
  File "/usr/local/bin/redfishtool", line 14, in <module>
    from redfishtoollib import main
ImportError: No module named redfishtoollib

While running redfishtool i am getting No module named redfishtoollib

**Comment by mraineri** [comment]
What's the output of the following?

```
pip3 show redfishtool -f
```

**Comment by Ganesan149** [comment]
lab@lab-Precision-5510-lab3:~/ganesan/Redfish-Usecase-Checkers$ pip3 show redfishtool -f
Name: redfishtool
Version: 1.1.5
Summary: Redfishtool package and command-line client
Home-page: https://github.com/DMTF/Redfishtool
Author: DMTF, https://www.dmtf.org/standards/feedback
Author-email:
License: BSD 3-clause "New" or "Revised License"
Location: /usr/local/lib/python3.6/dist-packages
Requires: python-dateutil, requests
Required-by:
Files:
  ../../../bin/__pycache__/redfishtool.cpython-36.pyc
  ../../../bin/redfishtool
  ../../../bin/redfishtool.py
  redfishtool-1.1.5.dist-info/DESCRIPTION.rst
  redfishtool-1.1.5.dist-info/INSTALLER
  redfishtool-1.1.5.dist-info/METADATA
  redfishtool-1.1.5.dist-info/RECORD
  redfishtool-1.1.5.dist-info/REQUESTED
  redfishtool-1.1.5.dist-info/WHEEL
  redfishtool-1.1.5.dist-info/metadata.json
  redfishtool-1.1.5.dist-info/top_level.txt
  redfishtoollib/AccountService.py
  redfishtoollib/Chassis.py
  redfishtoollib/Managers.py
  redfishtoollib/ServiceRoot.py
  redfishtoollib/SessionService.py
  redfishtoollib/Systems.py
  redfishtoollib/__init__.py
  redfishtoollib/__pycache__/AccountService.cpython-36.pyc
  redfishtoollib/__pycache__/Chassis.cpython-36.pyc
  redfishtoollib/__pycache__/Managers.cpython-36.pyc
  redfishtoollib/__pycache__/ServiceRoot.cpython-36.pyc
  redfishtoollib/__pycache__/SessionService.cpython-36.pyc
  redfishtoollib/__pycache__/Systems.cpython-36.pyc
  redfishtoollib/__pycache__/__init__.cpython-36.pyc
  redfishtoollib/__pycache__/raw.cpython-36.pyc
  redfishtoollib/__pycache__/redfishtoolMain.cpython-36.pyc
  redfishtoollib/__pycache__/redfishtoolTransport.cpython-36.pyc
  redfishtoollib/raw.py
  redfishtoollib/redfishtoolMain.py
  redfishtoollib/redfishtoolTransport.py
lab@lab-Precision-5510-lab3:~/ganesan/Redfish-Usecase-Checkers$

**Comment by mraineri** [comment]
What about the output of the following?

```
which python
which python3
python --version
python3 --version
ls /usr/local/lib/python3.*/dist-packages/redfishtool*
```

**Comment by Ganesan149** [comment]
lab@lab-Precision-5510-lab3:~/ganesan/Redfish-Usecase-Checkers$ which python

/usr/bin/python

lab@lab-Precision-5510-lab3:~/ganesan/Redfish-Usecase-Checkers$ which python3

/usr/bin/python3

lab@lab-Precision-5510-lab3:~/ganesan/Redfish-Usecase-Checkers$ python --version

Python 2.7.17

lab@lab-Precision-5510-lab3:~/ganesan/Redfish-Usecase-Checkers$ python3 --version

Python 3.6.9

lab@lab-Precision-5510-lab3:~/ganesan/Redfish-Usecase-Checkers$ ls /usr/local/lib/python3.6/dist-packages/redfishtool*

/usr/local/lib/python3.6/dist-packages/redfishtool-1.1.5.dist-info:

DESCRIPTION.rst  INSTALLER  METADATA  metadata.json  RECORD  REQUESTED  top_level.txt  WHEEL

/usr/local/lib/python3.6/dist-packages/redfishtoollib:

AccountService.py  __init__.py  __pycache__  redfishtoolMain.py       ServiceRoot.py     Systems.py

Chassis.py         Managers.py  raw.py       redfishtoolTransport.py  SessionService.py

**Comment by mraineri** [comment]
Hopefully this is the last one. I'm suspecting the script is running under Python2 when you're executing it.

Can you show me the output of:

```
cat /usr/local/bin/redfishtool
```

**Comment by Ganesan149** [comment]
@mraineri 

Is there any update for this issue.

**Comment by mraineri** [comment]
Can you try reinstalling the tool with:

```pip3 install -U redfishtool```

As far as I can tell the tool might have been installed in the 3.X directory using the 2.0 version of pip.

**Comment by mraineri** [comment]
It would also be good to know how you installed it in the first place. Was this through a Debian package? pip?

**Comment by mraineri** [comment]
No updates; closing...
