### ISSUE TITLE
Nice to have. Not possible to compare two servers.

### ISSUE THREAD

**Issue by hayonj** [DMTF/Redfishtool#102]
It would be nice to be able to compare two servers using this redfishtool, we can easily compare features between 2 servers which have the same versioning but different features.

**Comment by mraineri** [comment]
@hayonj we're not entirely sure if this is an appropriate addition to redfishtool; the scope of redfishtool has been focused on peeking/poking at a specific Redfish service.

The idea of comparing two servers also appears to be problematic; it's not clear if we can really get agreement on what the comparison really is going to look like. Some people might want to just match hardware configurations, others might want to perform strict resource comparisons across the board, others might want something inbetween.

As an alternative, would you be able to use the https://github.com/DMTF/Redfish-Mockup-Creator to do this type of work? Essentially you would use the mockup creator with each of your systems, and you can post-process the mockup trees to do any type of comparison between the two you want.

**Comment by mraineri** [comment]
Closing; not in scope for this tool.
