### ISSUE TITLE
Question - Can a token be generated from redfishtool?

### ISSUE THREAD

**Issue by zmance-ddn** [DMTF/Redfishtool#110]
Here is how I can generate token with curl command. How can I do the same with this tool?
As a test, I tried using token from curl command with RFT, but was still not able to connect. 

Is it because I need to use insecure method (like curl cmd?)
Any help? Do I have set headers and use raw http commands?
```
user@host-1:~$ curl --insecure -H "Content-Type: application/json" -X POST -D headers.txt https://${bmc}/redfish/v1/SessionService/Sessions -d    '{"UserName":"root", "Password":"password"}'
{"@odata.context":"/redfish/v1/$metadata#Session.Session","@odata.etag":"\"1698550108\"","@odata.id":"/redfish/v1/SessionService/Sessions/2401af5cb65750c5359ecadd4d07bce0","@odata.type":"#Session.v1_2_1.Session","Description":"Session for user root","Id":"2401af5cb65750c

user@host-1:~$ redfishtool -r <ip address>/redfish -t 2401af5cb65750c5359ecadd4d07bce0 --Auth Session versions
   redfishtool: Transport: Can't connect to remote redfish service. Aborting command
   redfishtool: Transport Error. No response
```

**Comment by jautor** [comment]
There's good examples of the flow using curl in the Redfish User Guide: https://www.dmtf.org/sites/default/files/standards/documents/DSP2060_1.0.0.pdf

**Comment by mraineri** [comment]
Yes, there's a SessionService subcommand that lets you both create and delete sessions.

You'd first make the session like this:

```
> redfishtool -u root -p password -r 192.168.1.50 SessionService login
{
    "SessionId": "2",
    "SessionLocation": "/redfish/v1/SessionService/Sessions/2",
    "X-Auth-Token": "MY_SESSION_TOKEN"
}
```

Copy the SessionId and X-Auth-Token; SessionId is used to log out, and X-Auth-Token is used in subsequent requests.

You then use the token with the `-t` argument, or use it in another tool you have.

```
> redfishtool -t MY_SESSION_TOKEN -r 192.168.1.50 --Auth Session Systems list
{
    "_Path": "/redfish/v1/Systems",
    "Name": "System Collection",
    "Members@odata.count": 1,
    "Members": [
        {
            "Id": "1",
            "@odata.id": "/redfish/v1/Systems/1",
            "AssetTag": ""
        }
    ]
}
```

When done, you delete the session like this:

```
> redfishtool -t MY_SESSION_TOKEN -r 192.168.1.50 --Auth Session SessionService logout -i 2
```

**Comment by zmance-ddn** [comment]
@mraineri Thank you for the quick response. I appreciate the gentle reminder to RTFM =)
