### ISSUE TITLE
"redfishtool: getCollection: Error getting service root, aborting" 

### ISSUE THREAD

**Issue by Bhavadhara** [DMTF/Redfishtool#111]
Hi, I'm facing the same issue when trying to verify server BMC through redfishtool.  "redfishtool: getCollection: Error getting service root, aborting" This is the one-line error message I'm getting. Even I verified the urllib3 is 1.24.3 and I'm not facing any issues with redfish API and postman. I need help with redfishtool on Raspbian OS.

_Originally posted by @Bhavadhara in https://github.com/DMTF/Redfishtool/issues/65#issuecomment-1845074755_

**Comment by jautor** [comment]
Can you try any of the tools in the Redfish Tackle box to help diagnose this as either a tool issue or an issue with the implementation?  https://github.com/DMTF/Redfish-Tacklebox/

**Comment by Bhavadhara** [comment]
<img width="542" alt="Redfish" src="https://github.com/DMTF/Redfishtool/assets/143505730/218116c5-93bb-48e0-91e5-cba7e9b2dfbb">

Hi,

I have given the username and password under basic auth in authorization and provided the Remote server IP "https://###########/redfish/v1/" under GET request and retrieved the output.

> If you're able to retrieve the ServiceRoot (/redfish/v1) via POSTMAN, can you show that full payload here, too?

**Comment by mraineri** [comment]
Can you provide your exact redfishtool request with all arguments as well as the entire output from redfishtool? Based on what you're specifying, I can follow-up with curl or other types of tool operations to help diagnose this further.

**Comment by Bhavadhara** [comment]
Hi, 

With this command "curl -k -u username:password https://<IP>/redfish/v1", I can retrieve BMC through Redfish API. For Redfishtool(version:1.1.8), I have copy pasted the command and the response I received below

**rpi@raspberrypi:~/Redfishtool $** redfishtool -r <IP> -u username -p password Systems
redfishtool: getCollection: Error getting service root, aborting
**rpi@raspberrypi:~/Redfishtool $** redfishtool -r <IP> -u username -p password AccountService
   redfishtool: get AccountService: Error getting service root, aborting
**rpi@raspberrypi:~/Redfishtool $**

**Comment by jautor** [comment]
can you post the JSON payload you received from that successful curl command?

**Comment by Bhavadhara** [comment]
{
  "@odata.id": "/redfish/v1",
  "@odata.type": "#ServiceRoot.v1_5_0.ServiceRoot",
  "AccountService": {
    "@odata.id": "/redfish/v1/AccountService"
  },
  "CertificateService": {
    "@odata.id": "/redfish/v1/CertificateService"
  },
  "Chassis": {
    "@odata.id": "/redfish/v1/Chassis"
  },
  "EventService": {
    "@odata.id": "/redfish/v1/EventService"
  },
  "Id": "RootService",
  "JsonSchemas": {
    "@odata.id": "/redfish/v1/JsonSchemas"
  },
  "Links": {
    "Sessions": {
      "@odata.id": "/redfish/v1/SessionService/Sessions"
    }
  },
  "Managers": {
    "@odata.id": "/redfish/v1/Managers"
  },
  "Name": "Root Service",
  "RedfishVersion": "1.9.0",
  "Registries": {
    "@odata.id": "/redfish/v1/Registries"
  },
  "SessionService": {
    "@odata.id": "/redfish/v1/SessionService"
  },
  "Systems": {
    "@odata.id": "/redfish/v1/Systems"
  },
  "Tasks": {
    "@odata.id": "/redfish/v1/TaskService"
  },
  "TelemetryService": {
    "@odata.id": "/redfish/v1/TelemetryService"
  },
  "UUID": "316e32c6-612d-5b3a-9381-e1cab0ac8e33",
  "UpdateService": {
    "@odata.id": "/redfish/v1/UpdateService"

**Comment by Bhavadhara** [comment]
Hi, 

Is there any way to resolve this? Any inputs regarding this could really help for planning our next steps. 

Regards,
Bhavadharani S

**Comment by mraineri** [comment]
Can you do try this?

`"curl -k https://190.190.0.0/redfish/v1"`

/redfish/v1/ is an unauthenticated resource per the spec, so redfishtool will not send credentials when doing initial discovery. I'm wondering if the service you're using is trying to enforce credentials when accessing /redfish/v1/.

**Comment by Bhavadhara** [comment]
Hi,

I've tried this command without credentials, and it worked. For redfishtool what we need to do to access /redfish/v1/.

**Comment by mraineri** [comment]
Can you try the following? If you do not add "-S Always", redfishtool start with HTTP when accessing the service root as an unauthenticated resource. Please also add "-v" and provide the output if it still is failing so we can see the debug output to look at this further.

`redfishtool -r 190.190.0.0 -u username -p password -S Always -v AccountService`

`curl http://190.190.0.0/redfish/v1/`

**Comment by Bhavadhara** [comment]
Hi,

The redfishtool command actually worked for me. Thanks much!! 

Could you help me with retrieving more info like BMC, BIOS
 and use POST for UpdateService. I'm finding it difficult while trying to navigate "redfishtool -r <BMC_IP> -u <username> -p <password> -S Always -v Systems/systemID/####/####"

Any documentation or link for using redfishtool with "Always -v" would really help.

Thanks in advance!

**Comment by jautor** [comment]
@Bhavadhara I'll suggest again that you also take a look at the tools in the Redfish Tacklebox repo: https://github.com/dmtf/redfish-tacklebox as those are under active development, while redfishtool is not.

There is more support there for items such as the UpdateService...

**Comment by Bhavadhara** [comment]
Hi,

Thanks @mraineri, @jautor, @EdwardBetts, @pjaroszynski for all the valuable inputs. Closing the issue with gratitude.

Regards,
Bhavadharani S
