### ISSUE TITLE
 setIndicatorLed fails with public-catfist mockup

### ISSUE THREAD

**Issue by wkevils** [DMTF/Redfishtool#17]
It seems that setIndicatorLed does not work (I am trying with the public-catfish mockup)

I do get the following when reading Systems/1: 
python /work/src/Redfishtool/redfishtool.py  -S Never -r 127.0.0.1  Systems -I 1
{
    "AssetTag": "CATFISHASSETTAG",
    "HostName": "catfishHostname",
    "IndicatorLED": "Off",
    "SystemType": "Physical",
    "Actions": {
        "#ComputerSystem.Reset": {
            "target": "/redfish/v1/Systems/1/Actions/ComputerSystem.Reset",
            "ResetType@Redfish.AllowableValues": [
                "On",
                "ForceOff",
                "GracefulShutdown",
                "ForceRestart",
                "Nmi",
                "GracefulRestart",
                "ForceOn"
            ]
        }
    },
    "Status": {
        "Health": "OK",
        "State": "Enabled"
    },
    "LogServices": {
        "@odata.id": "/redfish/v1/Systems/1/LogServices"
    },
    "PartNumber": "",
    "PowerState": "On",
    "@Redfish.Copyright": "Copyright 2014-2016 Distributed Management Task Force, Inc. (DMTF). For the full DMTF copyright policy, see http://www.dmtf.org/about/policies/copyright.",
    "UUID": "00000000-0000-0000-0000-000000000000",
    "@odata.type": "#ComputerSystem.v1_1_0.ComputerSystem",
    "SerialNumber": "2M220100SL",
    "Model": "YellowCat1000",
    "Description": "Catfish Implementation Recipe of simple scale-out monolithic server",
    "BiosVersion": "X00.1.2.3.4(build-23)",
    "@odata.id": "/redfish/v1/Systems/1",
    "@odata.context": "/redfish/v1/$metadata#ComputerSystem.ComputerSystem",
    "SKU": "",
    "Links": {
        "ManagedBy": [
            {
                "@odata.id": "/redfish/v1/Managers/bmc"
            }
        ],
        "Chassis": [
            {
                "@odata.id": "/redfish/v1/Chassis/1"
            }
        ],
        "Oem": {}
    },
    "Manufacturer": "CatfishManufacturer",
    "Name": "Catfish System",
    "Id": "1",
    "Boot": {
        "BootSourceOverrideEnabled": "Once",
        "BootSourceOverrideTarget": "Pxe",
        "BootSourceOverrideMode": "UEFI",
        "UefiTargetBootSourceOverride": "uefiDevicePath",
        "BootSourceOverrideTarget@Redfish.AllowableValues": [
            "None",
            "Pxe",
            "Usb",
            "Hdd",
            "BiosSetup",
            "UefiTarget",
            "UefiHttp"
        ]
    }
}

But when I am trying:
python  -S Never -r 127.0.0.1  Systems -I 1   setIndicatorLed Lit
I get:
   redfishtool: Transport: Response Error: status_code: 405 -- Method Not Allowed

And with debug verbosity of 6, I get:

python redfishtool.py  -vvvvvv -S Never -r 127.0.0.1  Systems -I 1   setIndicatorLed Lit
#DB5: Main: subcmd: Systems, subCmdArgs:['Systems', 'setIndicatorLed', 'Lit']
#DB5: Main: verbose=5, status=0, user=, password=, rhost=127.0.0.1
#DB5: Main: token=None, RedfishVersion=v1, Auth=Basic, Timeout=10
#DB5: Main: prop=None, Id=1, Match=Id:1, First=True, -1=False, Link=None
#DB5: Main: gotIdOptn=True, IdOptnCount=1, gotPropOptn=False, gotMatchOptn=True
#DB5: Main: 2nd-Level Collection Member reference options: -i<id>=None, -m<match>=None:None, -l<link>=None -all=False
#DB5: Main: 2nd-level Collection Member parsing: gotIdLevel2Optn=False, gotMatchLevel2Optn=False, IdLevel2OptnCount=0
#DB5: Main: configFile=, Secure=Never, waitNum:waitTime=1:3, Degug=00000000
#DB5: Main: Headers=None
#DB5: Main: options parsed.  Now lookup subcommand and execute it
#DB5: runSubCmd: subcmd: Systems
#DB5: runSubCmd: argvs:  ['Systems', 'setIndicatorLed', 'Lit']
#DB5: runSubCmd: found SubCmd: Systems in table. executing
#DB4: SystemsMain:  subcommand: Systems
#DB5: Systems: operation=setIndicatorLed, args=['setIndicatorLed', 'Lit']
#DB5: Systems:runOperation: operation: setIndicatorLed
#DB5: Systems:runOperation: args:  ['setIndicatorLed', 'Lit']
#DB5: Systems:runOperation: found Oper: Systems in table. executing
#DB4: Systems:setIndicatorLed: in operation
#DB4: Systems:setIndicatorLed: in operation
#DB4: Systems:setIndicatorLed: in getCollection
#DB4: ServiceRoot: in getServiceRoot
#DB5: getVersionsAndRootPath: read versions from rhost
#DB5: Transport.getRootPath: protocolVer to use=v1,  rootPath=/redfish/v1/
#DB5: Transport.rftProcessRequest: method=GET, baseUrl=http://127.0.0.1/redfish/v1/, rpath=/redfish/v1/
#DB5: Transport.rftProcessRequest: apiType=1
#DB5: Transport.ProcessRequest: url=http://127.0.0.1/redfish/v1/
#REQUEST: Transport:SendRecv:    GET http://127.0.0.1/redfish/v1/
#DB4: Systems:getCollection: link is: /redfish/v1/Systems
#DB5: Transport.rftProcessRequest: method=GET, baseUrl=http://127.0.0.1/redfish/v1/, rpath=/redfish/v1/Systems
#DB5: Transport.rftProcessRequest: apiType=2
#DB5: Transport.ProcessRequest: url=http://127.0.0.1/redfish/v1/Systems
#REQUEST: Transport:SendRecv:    GET http://127.0.0.1/redfish/v1/Systems
#
#  Systems Collection:
#DB5: Transport.rftProcessRequest: method=GET, baseUrl=http://127.0.0.1/redfish/v1/Systems/, rpath=/redfish/v1/Systems/1
#DB5: Transport.rftProcessRequest: apiType=2
#DB5: Transport.ProcessRequest: url=http://127.0.0.1/redfish/v1/Systems/1
#REQUEST: Transport:SendRecv:    GET http://127.0.0.1/redfish/v1/Systems/1
#DB4: SystemsOperations:get: got a path, now get entries
#
#  Systems Resource:
#DB5: Transport.rftProcessRequest: method=PATCH, baseUrl=http://127.0.0.1/redfish/v1/Systems/1/, rpath=None
#DB5: Transport.rftProcessRequest: apiType=2
#DB5: Transport.ProcessRequest: url=http://127.0.0.1/redfish/v1/Systems/1/
#REQUEST: Transport:SendRecv:    PATCH http://127.0.0.1/redfish/v1/Systems/1/
   redfishtool: Transport: Response Error: status_code: 405 -- Method Not Allowed
#DB5: Systems: operation returned with error: rc=5
#DB5: #DB4:Main: subcommand returned with error: rc=5
# Main: Error: rc=5
#DB5:    Response status code:405
#DB5:    Response headers: {'Connection': 'keep-alive', 'Server': 'nginx/1.10.3 (Ubuntu)', 'Date': 'Fri, 07 Jul 2017 13:21:59 GMT', 'Content-Length': '182', 'Content-Type': 'text/html'}
#DB5: rfCleanup:Cleaningup session: None

**Comment by mraineri** [comment]
Mockup servers typically don't allow for PATCH requests. If you're using the DMTF mockup server, we did add a change recently to allow for PATCH operations.

Are you using this tool to host the catfish mockup? https://github.com/DMTF/Redfish-Mockup-Server

**Comment by wkevils** [comment]
No, I don't use Redfish-Mockup-Server. I am hosting catfish mockup by simply unzipping  DSP2043_1.1.0.zip  (from https://github.com/openstack/python-redfish/blob/master/dmtf/DSP2043_1.1.0.zip ) into the folder that the nginx server accesses by default. 
Apart from it I only added index.json and index.xml to the nginx config file. I am following generally 
what I saw here: http://www.snia.org/sites/default/files/SMI/swordfish/mockup_how_to_install/Swordfish_v1_0_2_MockupHowToInstallv2.htm

**Comment by mraineri** [comment]
Unfortunately host a mockup server in that manner will only allow you to issue GET requests against it; you won't be able to perform actions or modify properties. In this case, in order to change the indicator LED, redfishtool needs to perform a PATCH on a resource, which is illegal with the type of server you have.

**Comment by wkevils** [comment]
Just tried now withRedfish-Mockup-Server and it worked, thanks!

**Comment by mraineri** [comment]
Closing; issue solved by moving to a mockup server that supports PATCH requests.
