### ISSUE TITLE
Mockup which supports actions

### ISSUE THREAD

**Issue by wkevils** [DMTF/Redfishtool#18]
Is there any mockup which supports actions ? 
I try with catfish, and I get
this repsonse: redfishtool: Transport: Response Error: status_code: 404 -- Not Found
It seems to me that the reason is that the reason is that there is no "/redfish/v1/Systems/1/Actions", which is what is expected. 
Here is the full log:

$python redfishtool.py -S Never -r 127.0.0.1 Systems -I 1 reset On

   GET: Headers: Host: 127.0.0.1
Accept-Encoding: identity
Connection: keep-alive
OData-Version: 4.0
User-Agent: python-requests/2.9.1
Accept: application/json

False
127.0.0.1 - - [08/Jul/2017 15:39:25] "GET /redfish/v1/ HTTP/1.1" 200 -
   GET: Headers: Host: 127.0.0.1
Accept-Encoding: identity
Connection: keep-alive
OData-Version: 4.0
Authorization: Basic Og==
User-Agent: python-requests/2.9.1
Accept: application/json

False
127.0.0.1 - - [08/Jul/2017 15:39:25] "GET /redfish/v1/Systems HTTP/1.1" 200 -
   GET: Headers: Host: 127.0.0.1
Accept-Encoding: identity
Connection: keep-alive
OData-Version: 4.0
Authorization: Basic Og==
User-Agent: python-requests/2.9.1
Accept: application/json

False
127.0.0.1 - - [08/Jul/2017 15:39:25] "GET /redfish/v1/Systems/1 HTTP/1.1" 200 -
   POST: Headers: Host: 127.0.0.1
Accept-Encoding: identity
Content-Length: 19
OData-Version: 4.0
User-Agent: python-requests/2.9.1
Accept: application/json
Connection: keep-alive
Authorization: Basic Og==
Content-Type: application/json

   POST: Data: {'ResetType': 'On'}
127.0.0.1 - - [08/Jul/2017 15:39:25] "POST /redfish/v1/Systems/1/Actions/ComputerSystem.Reset HTTP/1.1" 404 -
   redfishtool: Transport: Response Error: status_code: 404 -- Not Found

**Comment by tomasg2012** [comment]
Due to the nature of the mockups being simply aggregated json payloads, no mockup alone really "supports" actions, it is up to the Redfish-Mockup-Server to support those actions.  None of the mockups technically support actions.

That being said, the further the Mockup-Server implements actual functions, the closer it becomes to being an Emulator.  If you would like to emulate Actions, please refer to the Redfish-Interface-Emulator.

**Comment by jcleung5549** [comment]
You can use the Redfish Interface Emulator. It supports Actions, by supporting HTTP POSTs.  One needs to create the dynamic resource for the resource specified in the "target" property of the Action of interest (e.g.  "target": "/redfish/v1/Systems/CS_5/Actions/ComputerSystem.Reset")

**Comment by mraineri** [comment]
Closing 7/20: @wkevils please file an issue against the mockup tool you're using. From the feedback here, you should be using the Redfish Interface Emulator in the manner @jcleung5549 is recommending.
