### ISSUE TITLE
README.md of Redfishtool needs to include -u and -p option in Example Usage section

### ISSUE THREAD

**Issue by gunawana** [DMTF/Redfishtool#19]
I ran several tests taken from Examples Usage section, found that the examples command lines did not mention -u and -p option, they are needed in order to make the test work.

**Comment by billdodd** [comment]
Agree that updating some of the examples to show the user/pass options would be helpful. That pair of options isn't required by the tool or by all services, but it is commonly needed on production services.

Interested to hear what other Tools Taskforce folks think about this in terms of how many (or which) examples to update.
