### ISSUE TITLE
Bad request syntax when using Redfish-Profile-Simulator

### ISSUE THREAD

**Issue by alikashmar** [DMTF/Redfishtool#20]
All commands that I submit through the redfishtool are met with bad request syntax error on the simulator side. 

For example:
```
python redfishtool.py --user=root --password=password123456 --rhost=127.0.0.1:5000 Chassis list
```

Response is:
```
127.0.0.1 - - [15/Aug/2017 13:11:09] "GET /redfish/v1/ HTTP/1.1" 200 -
127.0.0.1 - - [15/Aug/2017 13:11:09] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\x8b"\xe4\xb7\xbb?v\x8eh\xaek\xca\'\x80{R\x13\xde-\xb3\x18\xa9\x83\\\x80\x04kTV.\xb57\x00\x00n\xc00\xc0,\xc02\xc0.\xc0/\xc0+\xc01\xc0-\x00\xa5\x00\xa3\x00\xa1\x00\x9f\x00\xa4\x00\xa2\x00\xa0\x00\x9e\xc0(\xc0$\xc0\x14\xc0')
127.0.0.1 - - [15/Aug/2017 13:11:09] "��"䷻?v�h�k�'�{R�-���\�kTV.�7n�0�,�2�.�/�+�1�-���������(�$��" 400 -
```
The simulator was started using the command: `python redfishProfileSimulatorMain.py`

Am I missing some configuration or is this a bug?

**Comment by pwvancil** [comment]
the redfishProfileSimulator is running only HTTP  in config.
by default, Redfishtool will use HTTPS with the default basic auth.
.
So add the -SNever  option to Redfishtool and it will send everything http
python redfishtool.py -u root -p password123456 -r 127.0.0.1:5000 -S Never   Chassis list
.
thanks
paulv

**Comment by alikashmar** [comment]
Thanks @pwvancil! That solves the issue. This should be documented though.

**Comment by pwvancil** [comment]
very good.
the limitation is noted in the Redfish-Profile-Simulator README
Limitation:
* Supports only HTTP (not HTTPS)
* with redfishtool, use options: redfishtool.py -r127.0.0.1:5000 -u root -p password123456 -S Never
. but it is obviously not obvious .  
and maybe we can make the simulator output a message that it got https?  that would help.
.
FYI-an major upgrade to profile simulator is coming soon that is much better in every way and can do ssl and auth of multiple users.

**Comment by alikashmar** [comment]
You're right. I completely missed that.

**Comment by mraineri** [comment]
Closing; limitation of the Redfish-Profile-Simulator is documented in its readme. Redfishtool should be given options to not use HTTPS when working with the Redfish-Profile-Simulator.
