### ISSUE TITLE
Use ActionInfo if no @Redfish.AllowableValues is present

### ISSUE THREAD

**Issue by samerhaj** [DMTF/Redfishtool#23]
The tool relies on @Redfish.AllowableValues in multiple cases (System/Manager ResetType, BootSourceOverrideTarget). But Redfish also allows the equivalent to be implemented as an ActionInfo (for the Reset Actions at least). The tool should be able to use ActionInfo AllowableValues if no Redfish.AllowableValues annotation is present

**Comment by mraineri** [comment]
Agreed; this should be added. Might also want to consider what to do when no AllowableValues are given in either the resource or the ActionInfo (maybe it allows all possible options).
