### ISSUE TITLE
Managers setTimeOffset  usage error and offset parsing issue

### ISSUE THREAD

**Issue by pwvancil** [DMTF/Redfishtool#26]
`Redfishtool Managers setTimeOffset offset=<offsetString>`   has two issues:
1) the main usage in Managers -h  has wrong format.  left off the offset=
    but the error message usage prints have it correct
2) the parser is not parsing offset=<offsetString>
.
Note that the form `offset=<offsetString>` was used because `offsetString` cant be a normal commandline argument since it can start with a `-` char.      so intent had been to pass in with `offset=<offsetString>` all along as indicated by the error messages.    
.
See Pull Request to fix

**Comment by mraineri** [comment]
Fixed in latest PR
