### ISSUE TITLE
Running The 'pip3 install redfishtool' on Windows does not yield ability to run from command line 

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfishtool#28]
The redfishtool script installed in scripts directory is not directly executable from Windows CLI
Needs to have python interpreter as Windows CLI does not have direct script execution (as seen in Linux)

Indirect execution is possible, for example: 
py -3 c:\python35\scripts\redfishtool

**Comment by mraineri** [comment]
For the case of Windows, would it make more sense to release a standalone executable that isn't pulled via pip? Could use CX_Freeze to do this.

**Comment by mraineri** [comment]
Can also add line in the README to explain how to include the Python scripts folder to your Path variable in Windows to get the redfishtool script to resolve.

**Comment by slyle9** [comment]
Please also add a little more detail in the README about including the "requests" library (for example, where to find it) in python.  Windows didn't already have it in the 3.4.2 python rev I had.

**Comment by mraineri** [comment]
Closing; latest PR addresses this
