### ISSUE TITLE
problem in work with manager

### ISSUE THREAD

**Issue by elham1296** [DMTF/Redfishtool#4]
Hi, I am trying to work with manager, but I have the following errors. I would appreciate if you help me to find the problem.

# python3.4 redfishtool.py -r 10.101.19.2 -ss -vvv Managers list
#REQUEST: Transport:SendRecv:    GET http://10.101.19.2/redfish/v1/
   redfishtool: Transport: Response Error: status_code: 404 -- Not Found
   redfishtool: getCollection: Error getting service root, aborting
# Main: Error: rc=5
# python3.4 redfishtool.py -r 10.101.19.2 -ss -vvv Managers Logs
   redfishtool: Managers: Syntax error: [-I|-M|-L|-F|-1] required for action that targets a specific Managers instance
# python3.4 redfishtool.py -r 10.101.19.2 -ss -vvv Managers -1 Logs
#REQUEST: Transport:SendRecv:    GET http://10.101.19.2/redfish/v1/
   redfishtool: Transport: Response Error: status_code: 404 -- Not Found
   redfishtool: getCollection: Error getting service root, aborting
# Main: Error: rc=5
# python3.4 redfishtool.py -r 10.101.19.2 -ss -vvv Managers -F Logs
#REQUEST: Transport:SendRecv:    GET http://10.101.19.2/redfish/v1/
   redfishtool: Transport: Response Error: status_code: 404 -- Not Found
   redfishtool: getCollection: Error getting service root, aborting
# Main: Error: rc=5
# python3.4 redfishtool.py -r 10.101.19.2 -ss -vvv Managers -1 Logs -a
#REQUEST: Transport:SendRecv:    GET http://10.101.19.2/redfish/v1/
   redfishtool: Transport: Response Error: status_code: 404 -- Not Found
   redfishtool: getCollection: Error getting service root, aborting
# Main: Error: rc=5

**Comment by aparnabharathan1995** [comment]
Hi,
It would be really helpfull if u mention how u solved the above issue....even i am getting the same error.

redfishtool: getCollection: Error getting service root, aborting

**Comment by Bhavadhara** [comment]
Hi @aparnabharathan1995, 
I'm also getting the same error when trying redfishtool. Any inputs, if you have resolved this issue will be helpful.
