### ISSUE TITLE
Error 405 -- Method Not Allowed

### ISSUE THREAD

**Issue by tdeneau** [DMTF/Redfishtool#42]
Not sure if this is appropriate question it may be more of an HP DL360 question but...

I am trying to use redfishtool to change a BIOS setting on an HP DL360. I am using the same general technique that I used on other Redfish implementations (like supermicro) and it worked fine there.

python3 redfishtool.py -r ilomxq61101ng -u name -p password raw PATCH -d '{"ProcHyperthreading": "Disabled"}' /redfish/v1/systems/1/bios

but on the DL360 this gives:
redfishtool: Transport: Response Error: status_code: 405 -- Method Not Allowed

Should I be able to change a BIOS setting in this way on that system?

**Comment by mraineri** [comment]
Generally speaking, I think you'll find most implementations don't allow a client to PATCH the BIOS resource directly; you'll likely see the property `@Redfish.Settings` in the BIOS object, and in these cases, the client should PATCH the resource pointed to by `@Redfish.Settings`.

**Comment by mraineri** [comment]
@tdeneau did the above response answer your question? Can we close out this issue?

**Comment by mraineri** [comment]
Closing; no updates from submitter
