### ISSUE TITLE
Request for "Broker" Redfish API

### ISSUE THREAD

**Issue by john24318** [DMTF/Redfishtool#46]
Hi Dell,
Could you design a centralized "Brokers" redfish API to consolidate the sensor readings?
If I want to get power consumption, thermal, Intel ME readings... etc., I have to invoke the Systems or Chassis API subcomponent many times. Is it possible to design a "broker" settings to deliver sensor reading value for management software in the future? It will be more convenient to monitor servers.
Sorry for that I don't know how to give feedback to DMTF, so I leave my message here.

Sincerely,
John

**Comment by mraineri** [comment]
Closing; this tool is for a simple command line tool to interface with Redfish services. If you'd like to discuss new functionality in the standard or new tool ideas, please raise this on the public forum found here: https://redfishforum.com/
