### ISSUE TITLE
Redfishtool not working: 

### ISSUE THREAD

**Issue by Peterkem** [DMTF/Redfishtool#5]
Hello!
I would like to get the power consumption of my server through redfishtool but whatever the command i run, i get this error message. Before i get the following message i ran "python redfishtool.py -h".
I have no knowledge of python language. Please could you help me fix this problem?
Regards

Traceback (most recent call last):
  File "redfishtool.py", line 14, in <module>
    from redfishtool import main
  File "/home/noemie/Documents/Redfishtool-master/redfishtool/__init__.py", line 5, in <module>
    from .redfishtoolMain import main
  File "/home/noemie/Documents/Redfishtool-master/redfishtool/redfishtoolMain.py", line 21, in <module>
    from .redfishtoolTransport   import RfTransport
  File "/home/noemie/Documents/Redfishtool-master/redfishtool/redfishtoolTransport.py", line 716
    def printVerbose(self,v,*argv, skip1=False, printV12=True,**kwargs): 
                                       ^
SyntaxError: invalid syntax

**Comment by mraineri** [comment]
What's the exact version of python you're using? You can get that with the following command:
`python --version`

For example:
```
rainem1@rainem1-dev:/$ python --version
Python 3.5.2
```

**Comment by Peterkem** [comment]
I'm using the version 2.7.5. Do you think i should update this version?
Regards

**Comment by mraineri** [comment]
Yes, redfishtool only supports Python3.4 or higher.

Some systems will have both Python2.7 and Python3.x installed, where "python" is mapped to the Python2.7 binary, and "python3" is mapped to the Python3.x binary.

Can you try running this from your console?
`python3 --version`

If that resolves, you should be able to run redfishtool like this:
`python3 redfishtool.py -h`

**Comment by Peterkem** [comment]
I've downloaded python3.6.1 and this time after running the following command:
python3.6 redfishtool.py -h

I get a ModuleNotFoundError as follows:
Traceback (most recent call last):
  File "redfishtool.py", line 14, in <module>
    from redfishtool import main
  File "/home/noemie/Documents/Redfishtool-master/redfishtool/__init__.py", line 5, in <module>
    from .redfishtoolMain import main
  File "/home/noemie/Documents/Redfishtool-master/redfishtool/redfishtoolMain.py", line 21, in <module>
    from .redfishtoolTransport   import RfTransport
  File "/home/noemie/Documents/Redfishtool-master/redfishtool/redfishtoolTransport.py", line 37, in <module>
    import requests
ModuleNotFoundError: No module named 'requests' 

Can you help me handle this :)?

**Comment by mraineri** [comment]
It looks like the "requests" module does not come by default in your installation; you'll need use "pip" to install it. "pip" is a package manager for Python.

Depending on how your system installs the pip package for Python3.6, you would use commands like this to install "requests".
```
pip install requests
```
```
pip3 install requests
```
```
pip3.6 install requests
```

**Comment by Peterkem** [comment]
@mraineri Thank you very much! 💯 
Now it's working properly
