### ISSUE TITLE
Enhance redfishtool to support adding user via PATCH

### ISSUE THREAD

**Issue by billdodd** [DMTF/Redfishtool#7]
- Rationale:
  IPMI systems may have a fixed set of user account slots, with the Accounts Collection populated with an account for each slot, even when many of the accounts slots may not be in use. Normally when adding an entry to a collection, a POST operation is performed. But since the account entries in an IPMI system as described already exist, they must be updated with a PATCH operation to update them with a username, password, and role. And similarly, an existing user account in a system like this would need to be updated with PATCH to effectively delete it. 

  The current redfishtool supports adding accounts with POST and deleting accounts with DELETE. It would be a useful enhancement to add support for performing account add and delete using POST for IPMI systems as described.

- Logic to use PATCH to add new user:
  - Input provided: username, role, password
  - Fetch Accounts collection
  - Search collection for username
    - If found, return error “username already in use”
  - Search collection for unused slot (UserName == “”, “Enabled” == false)
    - If found, note “@odata.id” value of the account to PATCH (this will be the URI)
    - Else return error “no unused account slots available”
  - Build PATCH data for request, for example:
    `{"UserName": "newUserName", "Enabled": true, "Password": "newPassword", "RoleId": "Operator"}`
  - Submit PATCH including PATCH data in body to the URI,  for example:
    `/redfish/v1/Managers/iDRAC.Embedded.1/Accounts/3`
    

- Logic to use PATCH to delete existing user:
  - Input provided: username
  - Fetch Accounts collection
  - Search collection for username
    - If found, note “@odata.id” value of the account to PATCH (this will be the URI)
    - Else return error “username not found”
  - Build PATCH data for request, for example:
    `{"UserName": "", "Enabled": false, "Password": null, "RoleId": "None"}`
  - Submit PATCH to URI, for example:
    `/redfish/v1/Managers/iDRAC.Embedded.1/Accounts/3`

- Additional considerations:
  - Need to consider/handle ETag headers

- Interface updates:
  The existing AccountService subcommand syntax would need to be updated. This could be handled in a few different ways:
  - Enhance one or more of the existing AccountService operations `patch`, `useradmin`, `adduser`, or `deleteuser`
  - Add new AccountService operations specifically for adding and deleting users via PATCH

I can work on this enhancement. I included a somewhat detailed description here in hopes of getting any feedback and advice from the community.

**Comment by J2Hilland** [comment]
This doesn't seem like the right thing to do to me.  Because it doesn't propose really adding a user but instead proposes modifying one.  There is no way this type of implementation will be interoperable with others.  What is missing from the algorithm is how to determine if this is the kind of implementation where you do a POST to add a user or a PATCH.  I speculate that any such method would be implementation specific.  
I think the right thing to do is for implementations based on IPMI to not expose existing unconfigured users and support a POST to add (configure) them, returning an error when the account limit is exhausted.  We even talked about this during specification development as the way to support this kind of implementation.  And that any implementation that exposed them should just use PATCH.  
So to me this all hinges on "How do you tell this kind of implementation in an interoperable way?"  Otherwise, this looks like DMTF contractors fixing a single implementations issue.

**Comment by mraineri** [comment]
I wouldn't really call this "Adding new user with PATCH"; it's really updating an existing user with PATCH. Even if the service isn't doing this pre-population of user data to support IPMI style users, redfishtool should still be able to update existing users with PATCH.

**Comment by J2Hilland** [comment]
No disagreement with your statement, but the way I read the initial request is for the tool to "add" a user with PATCH.  And, if that's true, how do you do that in an interoperable way?

**Comment by mraineri** [comment]
I assume that in this type of scenario, a client is still able to get all of the accounts via GETs on the Members of the ManagerAccountCollection. The Id property is the unique identifier in that collection, and I'd imagine from a redfishtool perspective, it would use the Id property as part of the request from the user to identify which slot to update, and the user would also give the new properties for the account (like UserName, Password, Enabled, Locked, etc). Something like:
`python redfishtool.py AccountService updateuser <userid> [<userName>] [<password>] [etc etc etc]`

**Comment by J2Hilland** [comment]
I understand the update of the user and am all for it.  It's getting the tool to "Search collection for unused slot (UserName == “”, “Enabled” == false)" and assume that's okay for a tool to use for a "python redfishtool.py AccountService adduser" that I have an issue with.

**Comment by mraineri** [comment]
Ah, I see. I wasn't thinking it would be that intelligent; I was thinking it would simply find a match based off the given Id provided.

**Comment by billdodd** [comment]
Thanks, Mike and Jeff for the thoughtful input. I had originally thought to specify the Id of the account to patch as Jeff described above. But then I thought it could be more convenient for the tool to search for an "unused" slot for the case where they effectively want to "add" a user. But now I can see how that would be problematic to do in an interoperable way. It does make more sense to only view this as a user update function and not treat it or model it as add/delete.

**Comment by pwvancil** [comment]
I agree.   
I had  not considered this a typical use case when redfishtool was done, but I remember explaining what was going on to Pyrinka when she was testing.
I agree finding an unused user is not adding a user though.
.
FYI-Redfishtool already has a "useradmin" subcommand which can update the role or enable/disable the user or unlock the user.   But it did not include changing the username as a use case.
So if we add "changing username" as option to useradmin, then all managerAccount properties can be updated from there I think.
.  
If the implementation has fixed username=Id, then nothing to change.

**Comment by billdodd** [comment]
Thanks, Paul for your input as well.

I coded and tested a change for this. The existing AccountService useradmin syntax looks like this:

`useradmin <userName> [enable|disable|unlock|[setRoleId <roleId>]]`

I added one new action, `setUsernameForId`, so the syntax now looks like this:

`useradmin <userName> [enable|disable|unlock|[setRoleId <roleId>]|[setUsernameForId <Id>]]`

Example usage:

`redfishtool -r<ip> AccountService useradmin alice setUsernameForId 3`

Given this input, the tool looks for an account entry with an Id of '3'. If found, the UserName of that entry is set to 'alice' via a POST.

Before I did I Pull request, wanted to get any initial feedback for this approach.
Any input Mike, Jeff or Paul?

**Comment by mraineri** [comment]
I'm wondering if overloading "useradmin" with an option for setting by user ID is a bit much... It might be more appropriate to have a separate operation for updating a user by their ID.

**Comment by billdodd** [comment]
I didn't feel this was a case of overloading. My thinking: The `useradmin` operation supports several actions. And I added one additional action. And I viewed the new action as comparable to the existing `setRoleId` action.

I'm not against adding a new operation. But I felt this fit reasonably well within the scope of the `useradmin` operation.

Paul - as the tool author, do you have any input?

**Comment by billdodd** [comment]
Given Mike's feedback above, I'm updating the change to add a new operation to set the username. The proposal is for a new `setusername` operation. The syntax would be:

`AccountService setusername <Id> <Username>`

Example usage:

`redfishtool -r<ip> AccountService setusername 3 alice`

This will locate an account entry with an Id of '3'. And if found will set the UserName to 'alice'.
