### ISSUE TITLE
Redfishtool is easy to come up error "Execution timeout" and " redfishtool: raw: Error getting response"

### ISSUE THREAD

**Issue by jiaokekeke** [DMTF/Redfishtool#74]
Hi,
Could you help me sloved the redfishtool bug? It is very easy to come up error "Execution timeout" or " redfishtool: raw: Error getting response", but curl tool would not come up.
For example1 :
Execution timeout! Command [redfishtool -sssss -r [redacted IP address] -u admin -p [redacted password] -T 90 -S Always raw GET /redfish/v1/UpdateService] doesn't finish in 90sec:
---
   redfishtool: raw: Error getting response
[root@OrcOgrim ~]# redfishtool -sssss -r [redacted IP address] -u admin -p [redacted password]  -T 90 -S Always raw GET /redfish/v1/UpdateService

---
For example2 :
Execution timeout! Command [redfishtool -sssss -r [redacted IP address] -u admin -p [redacted password] -T 30 -S Always raw GET /redfish/v1/Chassis/Self] doesn't finish in 30sec: --- redfishtool -sssss -r [redacted IP address] -u admin -p [redacted password] -T 30 -S Always raw GET /redfish/v1/Chassis/Self  ---
--

**Comment by billdodd** [comment]
[I moved the issue to the correct repo.]

With the `-sssss` option, there should be some additional output from the commands. Can you capture and post all the output from the commands?

I can't see anything obviously wrong with the commands you are running. And when I run commands equivalent to those against the services I have access to, they run within a normal timeframe (about 1 second or less).

Also, when you run equivalent commands with curl, how long do they take?

**Comment by jautor** [comment]
I've edited your post to remove the IP addresses and passwords from view - these are likely internal test systems, but not something we'd want to expose regardless...

**Comment by mraineri** [comment]
@jiaokekeke are you still having issues with this? Were you able to collect additional info that was requested?

**Comment by mraineri** [comment]
Closing; no additional information from the submitter to help with the issue.
