### ISSUE TITLE
How to run redfishtool locally without a network cable connection?

### ISSUE THREAD

**Issue by JuunyK** [DMTF/Redfishtool#87]
ipmitool can be run locally without setting up a BMC network.
Does redfishtool have the same function?

Example>
Condition : DONOT set BMC network or if set, the BMC network cable is not connected.
[ok] ipmitool -I open sel list or ipmitool sel list
[ok] ipmitool -I lanplus -H BMC_LOCAL_IP -U USER -P PASSWORD sel list
[Failed] redfishtool -r BMC_LOCAL_IP -U USER -P PASSWORD raw GET /redfish/v1/Systems/1

**Comment by mraineri** [comment]
This really depends on the system you have available. By definition, Redfish as a protocol is only supported on network interfaces. Redfish does have a Host Interface specification where it defines methods of implementing a local NIC between the host and BMC, and methods for how software can discover this interface. Vendors have the choice of supporting this type of interface.

But from a redfishtool perspective, this is no different than an external interface. You'll need to find the IP of BMC for the host interface, which will not be the same as the IP for the external interfaces.

**Comment by mraineri** [comment]
Closing; functionality exists already since the local interface to the manager for Redfish is also a network interface.
