### ISSUE TITLE
Documentation needs an ipmitool to redfishtool conversion matrix

### ISSUE THREAD

**Issue by zetasyanthis** [DMTF/Redfishtool#9]
At the moment, it's a bit confusing how to go about grabbing information with redfishtool. For example, I can access the SEL log entries via curl, but none of the sub-arguments beyond -i SEL seem to allow me to grab the entries. A table that converts between typical ipmitool commands and redfishtool commands would be very helpful. (I do recognize that not every command is convertible, but some are.)

Redfishtool pull:
> zeta@testMachine:~/repos/tools/redfishtool$ python3 redfishtool.py -u Administrator -p superuser -r 192.168.4.170 Managers -1 Logs -i SEL
{
    "MaxNumberOfRecords": 300,
    "@odata.etag": "W/\"1494005905\"",
    "Status": {
        "Health": "OK",
        "State": "Enabled"
    },
    "OverWritePolicy": "WrapsWhenFull",
    "Name": "IPMI SEL",
    "DateTimeLocalOffset": "+34:07",
    "@odata.type": "#LogService.v1_0_2.LogService",
    "Description": "IPMI SEL events for this manager",
    "DateTime": "2017-05-05T17:38:25+34:07",
    "@odata.context": "/redfish/v1/$metadata#Managers/Members/Self/LogServices/Members(DateTimeLocalOffset,Id,Status,Name,ServiceEnabled,MaxNumberOfRecords,DateTime,OverWritePolicy,Entries,Description)/$entity",
    "Entries": {
        "@odata.id": "/redfish/v1/Managers/Self/LogServices/SEL/Entries"
    },
    "Actions": {
        "#LogService.ClearLog": {
            "target": "/redfish/v1/Managers/Self/LogServices/SEL/Actions/LogService.ClearLog",
            "ClearType@Redfish.AllowableValues": [
                "ClearAll"
            ]
        }
    },
    "@odata.id": "/redfish/v1/Managers/Self/LogServices/SEL",
    "ServiceEnabled": true,
    "Id": "SEL"
}

Example curl pull:
> zeta@testMachine:~/repos/tools/redfishtool$ curl -u Administrator:superuser -XGET 192.168.4.170/redfish/v1/Managers/Self/LogServices/SEL/Entries
{"@odata.context":"/redfish/v1/$metadata#Managers/Members/Self/LogServices/Members/SEL/Entries/$entity","@odata.etag":"W/\"0\"","@odata.id":"/redfish/v1/Managers/Self/LogServices/SEL/Entries","@odata.type":"#LogEntryCollection.LogEntryCollection","Description":"Collection of entries for this log service","Members":[{"@odata.id":"/redfish/v1/Managers/Self/LogServices/SEL/Entries/1","@odata.type":"#LogEntry.v1_0_2.LogEntry","Created":"2012-01-01T00:00:18-05:00","EntryCode":"Lower Critical - going low","EntryType":"SEL","Id":"1","Links":{"OriginOfCondition":{"@odata.id":"/redfish/v1/"}},"Message":"","MessageArgs":[],"MessageId":"Ipmi.2.0.GeneralEventData","Name":"SEL 13","SensorNumber":82,"SensorType":"Voltage","Severity":"OK"},{"@odata.id":"/redfish/v1/Managers/Self/LogServices/SEL/Entries/2","@odata.type":"#LogEntry.v1_0_2.LogEntry","Created":"2012-01-01T00:00:18-05:00","EntryCode":"Lower Critical - going low","EntryType":"SEL","Id":"2","Links":{"OriginOfCondition":{"@odata.id":"/redfish/v1/"}},"Message":"","MessageArgs":[],"MessageId":"Ipmi.2.0.GeneralEventData","Name":"SEL 14","SensorNumber":83,"SensorType":"Voltage","Severity":"OK"},{"@odata.id":"/redfish/v1/Managers/Self/LogServices/SEL/Entries/3","@odata.type":"#LogEntry.v1_0_2.LogEntry","Created":"2017-05-01T22:49:56+00:00","EntryCode":"Lower Critical - going low","EntryType":"SEL","Id":"3","Links":{"OriginOfCondition":{"@odata.id":"/redfish/v1/"}},"Message":"","MessageArgs":[],"MessageId":"Ipmi.2.0.GeneralEventData","Name":"SEL 15","SensorNumber":82,"SensorType":"Voltage","Severity":"OK"},{"@odata.id":"/redfish/v1/Managers/Self/LogServices/SEL/Entries/4","@odata.type":"#LogEntry.v1_0_2.LogEntry","Created":"2017-05-01T22:49:56+00:00","EntryCode":"Lower Critical - going low","EntryType":"SEL","Id":"4","Links":{"OriginOfCondition":{"@odata.id":"/redfish/v1/"}},"Message":"","MessageArgs":[],"MessageId":"Ipmi.2.0.GeneralEventData","Name":"SEL 16","SensorNumber":83,"SensorType":"Voltage","Severity":"OK"}],"Members@odata.count":4,"Name":"Log Service Entries Collection"}

**Comment by jose-delarosa** [comment]
Not an answer to your question, but try this script: https://github.com/dell/idrac-ansible-module/blob/master/scripts/view-system-events.py

**Comment by mraineri** [comment]
We can add enhancements to the tool to do things like printing a single entry; redfishtool currently only supports printing the entire log.

However, the difficulty with creating a table mapping for "if I did X with ipmitool, then I do Y with redfishtool" isn't going to be a 1 to 1 mapping. The concepts used in Redfish are a bit different than IPMI.

**Comment by mraineri** [comment]
Assigning to Bill to work on the single log entry printing; tracking request for educational material internally with different issue.
