### ISSUE TITLE
Enhancement: --no-proxy option

### ISSUE THREAD

**Issue by donzef** [DMTF/Redfishtool#90]
Proposed enhancement:

It could be interesting to have an option ignoring network proxy configuration. At least a simple option like the --no-proxy option of wget.

I'd love to implement it, but I am not a programmer at all :-(

**Comment by mraineri** [comment]
Will need to do some research into this. Some thoughts on how we can implement it:
* Could have the tool unset environment variables (but ensure this is just done in the process and not saved to the system)
* Could see if the requests library has a parameter that we can pass to not use any proxy info in the system

**Comment by donzef** [comment]
Not sure if this can help: [https://stackoverflow.com/questions/28521535/requests-how-to-disable-bypass-proxy](https://stackoverflow.com/questions/28521535/requests-how-to-disable-bypass-proxy)
