### ISSUE TITLE
Adding PowerCycle to ResetType

### ISSUE THREAD

**Issue by drthane** [DMTF/Redfishtool#92]
PowerCycle is not listed as one of the ResetTypes supported in Redfishtool.  When will it be added?

**Comment by mraineri** [comment]
It's a good idea to add it, but we have other priorities in other tools at this time. If you're willing to make the change yourself, we'd be happy to review the submission and have it added to the tool.

**Comment by billdodd** [comment]
Update: The tool does, in fact, already support the PowerCycle reset type (added in 2017 in version 1.0.2 of the tool). However, the README and help output does not list it.

**Comment by drthane** [comment]
I’m glad to hear that.  Thanks for looking into it.
