### ISSUE TITLE
Keep upgrading or obsoleted?

### ISSUE THREAD

**Issue by andy1990zx** [DMTF/Redfishtool#96]
Hi,

I am seeking for a fundamental lib/tool to build my script, the Redfishtool is a wonderful one that suits me.
But I noticed the last commit is 7 months ago, the RedFish spec and Schema spec is evolving, I worry if this tool is still maintained.
Another question is: do you have plan to update the coding style to meet Python PEP 8?

Thanks,
Sea

**Comment by mraineri** [comment]
Unfortunately this tool is a lower priority for us at this point. We tend to focus more of our time on conformance testing tools like the Redfish-Service-Validator, and other client tools like Redfish-Tacklebox. We do make updates as requested (and certainly welcome contributions back into the tool), so it does get our attention when new issues and pull requests are filed.

We also had not planned on updating the coding style, but we'd have no issues if someone were to make the change and submit it to us.

**Comment by mraineri** [comment]
Closing; will accept pull requests for new functionality, but nothing to definitively track in here
